In [143]:
import pandas as pd
import numpy as np

In [144]:
dataset = pd.read_excel('data/Data.xls')
x = dataset.iloc[:,3:7]
x.head()

Department   Age  Experience  Salary
0  Asset Management  38.0        23.0   46975
1  Customer Service  26.0        10.0   30711
2   Human Resources   NaN        14.0   25049
3               NaN   NaN        12.0   33309
4  Customer Service   NaN         NaN   25274

In [145]:
#from sklearn.impute import SimpleImputer

#imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
#imputer = imputer.fit(x)
#x = imputer.transform(x)

In [146]:
x= x.to_numpy()

In [147]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer = imputer.fit(x[:,0].reshape(-1,1))
temp = imputer.transform(x[:,0].reshape(-1,1))
x[:,0] = temp.reshape(1,-1)[0]

In [148]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:,1].reshape(-1,1))
temp = imputer.transform(x[:,1].reshape(-1,1))
temp = temp.round(decimals=1)
x[:,1] = temp.reshape(1,-1)[0]

In [149]:
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit(x[:,2].reshape(-1,1))
temp = imputer.transform(x[:,2].reshape(-1,1))
x[:,2] = temp.reshape(1,-1)[0]

In [150]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder = LabelEncoder()
labelencoder.fit(x[:,0])
x[:,0] = labelencoder.transform(x[:,0])
x[:10,:]

array([[2, 38.0, 23.0, 46975],
       [4, 26.0, 10.0, 30711],
       [6, 40.9, 14.0, 25049],
       [1, 40.9, 12.0, 33309],
       [4, 40.9, 16.0, 25274],
       [1, 40.9, 9.0, 48583],
       [10, 40.9, 24.0, 39697],
       [2, 40.9, 2.0, 24163],
       [7, 40.0, 30.0, 17160],
       [1, 24.0, 23.0, 35218]], dtype=object)

In [151]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
minmax.fit(x[:,2].reshape(-1,1))
k = minmax.transform(x[:,2].reshape(-1,1))
x[:,2] = k.reshape(1,-1)[0]
x[:10,:]

array([[2, 38.0, 0.7586206896551725, 46975],
       [4, 26.0, 0.3103448275862069, 30711],
       [6, 40.9, 0.44827586206896547, 25049],
       [1, 40.9, 0.3793103448275862, 33309],
       [4, 40.9, 0.5172413793103449, 25274],
       [1, 40.9, 0.27586206896551724, 48583],
       [10, 40.9, 0.7931034482758621, 39697],
       [2, 40.9, 0.034482758620689655, 24163],
       [7, 40.0, 1.0, 17160],
       [1, 24.0, 0.7586206896551725, 35218]], dtype=object)

In [152]:
from sklearn.preprocessing import StandardScaler

standard = StandardScaler()
standard.fit(x[:,3].reshape(-1,1))
k = standard.transform(x[:,3].reshape(-1,1))
x[:,3] = k.reshape(1,-1)[0]
x[:10,:]

array([[2, 38.0, 0.7586206896551725, 1.532588693353712],
       [4, 26.0, 0.3103448275862069, 0.0922343946746362],
       [6, 40.9, 0.44827586206896547, -0.409197358837472],
       [1, 40.9, 0.3793103448275862, 0.32231558429393276],
       [4, 40.9, 0.5172413793103449, -0.3892711588127061],
       [1, 40.9, 0.27586206896551724, 1.6749946028640388],
       [10, 40.9, 0.7931034482758621, 0.8880425432192854],
       [2, 40.9, 0.034482758620689655, -0.48766230649055],
       [7, 40.0, 1.0, -1.1078542121502628],
       [1, 24.0, 0.7586206896551725, 0.49137832139294624]], dtype=object)

In [153]:
from sklearn.preprocessing import Normalizer

normalizer = Normalizer()
normalizer.fit(x[:,1].reshape(-1,1))
k = normalizer.transform(x[:,1].reshape(-1,1))
x[:,1] = k.reshape(1,-1)[0]
x[:10,:]

array([[2, 1.0, 0.7586206896551725, 1.532588693353712],
       [4, 1.0, 0.3103448275862069, 0.0922343946746362],
       [6, 1.0, 0.44827586206896547, -0.409197358837472],
       [1, 1.0, 0.3793103448275862, 0.32231558429393276],
       [4, 1.0, 0.5172413793103449, -0.3892711588127061],
       [1, 1.0, 0.27586206896551724, 1.6749946028640388],
       [10, 1.0, 0.7931034482758621, 0.8880425432192854],
       [2, 1.0, 0.034482758620689655, -0.48766230649055],
       [7, 1.0, 1.0, -1.1078542121502628],
       [1, 1.0, 0.7586206896551725, 0.49137832139294624]], dtype=object)

In [154]:
from sklearn.model_selection import train_test_split

y = x[:,0]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=10)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(80, 4)
(80,)
(20, 4)
(20,)
